# Site settings
title: Mihai Popescu
header-img: img/home-bg.jpg
email: salut@mihaip.com
copyright_name: Mihai Popescu
description: "Professional and Personal Blog"
baseurl: ""
url: "http://mihaip.ro"
twitter_username: mr_mihaipopescu
github_username:  mihaipopescu
facebook_username:  mr.mihaipopescu
email_username:  salut@mihaip.ro

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
